import React from "react";
import { Link } from "gatsby";

export const czImgTitles = {
  image1: "Sbírka trvalých pylových preparátů české květeny. ",
  image2: "Trvalé preparáty Referenční pylové sbírky české květeny.",
  image3:
    "Příprava trvalých preparátů, Institute of Plant Sciences, University of Bern, Švýcarsko (2010).",
  image4: "Sbírka semen a plodů.",
  image5: "Určovací atlas semen.",
};
export const enImgTitles = {
  image1: "Reference pollen collection of the Czech flora.",
  image2:
    "Permanent slides of the Reference pollen collection of the Czech flora.",
  image3:
    "Preparing the slides of pollen grains at the Institute of Plant Sciences, University of Bern, Switzerland (2010).",
  image4: "Seed and fruit collection.",
  image5: "Atlas of seeds.",
};

export const en = {
  description:
    "There are extensive collections of pollen mounts and seeds and fruits of central european flora deposited at the Department of Paleoecology. We also posses the collection of organic sediments sampled during decades of palaeoecological investigation carried out at the Institute of Botany CAS.",
  pollen: {
    heading: "Pollen mounts collection",
    description: (
      <p>
        At the Institute of Botany CAS pollen is collected and mounted since
        1960s. Today the collection contains mounts of more than 3000 plant
        species of Central European flora. Pollen grains are acetolysed in order
        to disolve cell content, mounted to glycerine medium and then scanned in
        light microscope in 400x magnification. Mounts are used by palynologists
        as a reference material for fossil pollen determination. For
        determinantion of native pollen grains (with cell content), as are
        pollen alergens or honey pollen, the utilisation of our collection is
        not convenient. The pollen mount collection is located in Brno and
        Průhonice and open for public use, but only at our workplace. If you are
        interested, please contact&nbsp;
        <Link to="/people/" state={{ person: "dudova" }}>
          Lydie Dudová
        </Link>
        &nbsp; (Brno) or&nbsp;
        <Link to="/people/" state={{ person: "svitavska" }}>
          Helena Svitavská
        </Link>
        &nbsp; (Průhonice).
      </p>
    ),
  },
  seeds: {
    heading: "Seed and fruit collection",
    description: (
      <p>
        The collection of seeds and fruits of vascular plants comprises over
        4000 samples mainly of the central European species, but also from other
        parts of the World. The collection has been built on the Brno department
        of the Institute of Botany in the past fifty years. Currently we strive
        of further development and use of the collection for scientific and
        other purposes. The collection serves as reference for identification of
        material from soil samples (living seeds; soil seed bank) as well as
        from fossil sediments. Our aim is reconstruction of species composition
        from both resources. The collection is open for public use, please
        contracts&nbsp;
        <Link to="/people/" state={{ person: "hajkova" }}>
          Petra Hájková
        </Link>
        .
      </p>
    ),
  },
  profile: {
    heading: "The collection of peat profiles of the Czech and Slovak Republic",
    description: (
      <p>
        The collection of the peat profiles was generated by the occasion of the
        mapping mires in the Czech and Slovak Republics since 1960. The mires
        were sampled and stored, consequently. Altogether, it consists several
        dozens of the sites untouched by paleoecological methods until now. The
        collection is under the digitalization process. If you are interested,
        please contact&nbsp;
        <Link to="/people/" state={{ person: "svitavska" }}>
          Helena Svitavská
        </Link>
        .
      </p>
    ),
  },
};

export const cz = {
  description:
    "Naše oddělení disponuje sbírkou trvalých pylových preparátů a sbírkou semen a plodů rostlin středoevropské flóry. Dále vlastníme sbírku profilů organických sedimentů, získaných během mnoha let paleoekologického výzkumu na Botanickém ústavu AV ČR, v. v. i.",
  pollen: {
    heading: "Referenční pylová sbírka",
    description: (
      <>
        <p>
          Sbírka trvalých pylových preparátů vznikala od 60. let minulého
          století a zahrnuje přes 3 000 druhů středoevropské květeny. Pylová
          zrna jsou procesem acetolýzy zbavená buněčného obsahu, umístěná v
          glycerinovém médiu a jako trvalé preparáty vhodná pro pozorování ve
          světelném mikroskopu, nejčastěji při zvětšení 400x. Slouží jako
          srovnávací nástroj při determinaci (sub)fosilních pylových zrn.
          Využití sbírky pro určování nativních pylových zrn s buněčným obsahem,
          např. pro analýzu pylových alergenů nebo pylů v medu, je omezené.
        </p>
        <p>
          Sbírka se nachází v Brně a v Průhonicích a je možné s ní pracovat
          pouze prezenčně. Pokud máte zájem o práci se sbírkou,
          kontaktujte&nbsp;
          <Link to="/people/" state={{ person: "dudova" }}>
            Lydii Dudovou
          </Link>
          &nbsp; (Brno) nebo&nbsp;
          <Link to="/people/" state={{ person: "svitavska" }}>
            Helenu Svobodovou Svitavskou
          </Link>
          &nbsp; (Průhonice).
        </p>
      </>
    ),
  },
  seeds: {
    heading: "Sbírka semen a plodů",
    description: (
      <p>
        Sbírka semen a plodů cévnatých rostlin zahrnuje přes 4000 vzorků rostlin
        převážně středoevropské květeny, ale i jiných oblastí světa. Sbírka byla
        budována na brněnském pracovišti Botanického ústavu v posledních 50
        letech. Zde se také v současnosti nachází. Snažíme se společně s
        Oddělením vegetační ekologie o její další rozvoj a využití pro vědecké i
        jiné účely. Sbírka slouží jako srovnávací materiál při determinaci
        recentních rostlinných zbytků ze vzorků půdy (živá semena, semenná
        banka) i subfosilních zbytků z organických sedimentů. Cílem je
        rekonstrukce druhového složení vegetace z obou zdrojů. Se sbírkou lze po
        dohodě prezenčně pracovat, kontaktujte&nbsp;
        <Link to="/people/" state={{ person: "hajkova" }}>
          Petru Hájkovou
        </Link>
        .
      </p>
    ),
  },
  profile: {
    heading: "Sbírka rašelinných profilů z České a Slovenské republiky",
    description: (
      <p>
        Rašelinné profily odebrané v terénu během desítek let paleoekologických
        výzkumů jsou uskladněny na obou pracovištích Paleoekologického oddělení.
        Celkem máme ve skladu umístěno asi 200 rašelinných profilů, buďto ve
        formě monolitů v plechových krabicích nebo jako jednotlivé vzorky v
        plastikových sáčcích.
        <br />
        Na pracovišti v Brně jsou deponovány profily z lokalit: Bílé Karpaty,
        Podhůří Moravských Beskyd, Broumovsko, Českomoravská vrchovina, Železné
        hory, Žďárské a Jihlavské vrchy, Dolnomoravský úval a Záhorská plošina,
        Drahanská vysočina, Hrubý Jeseník a Kralický Sněžník, Jihočeské rybniční
        pánve, Krušné hory, Orlické hory, Oravská kotlina, Polabí, Posázaví,
        Rychlebské hory, Liptovská kotlina, Spišská kotliny, Vysoké a Belanské
        Tatry. Na pracovišti v Průhonicích jsou profily ze Šumavy, z Krkonoš, z
        Jizerských hor, ze Strážnického Pomoraví, z Dolnomoravského a
        Dyjsko-svrateckého úvalu. Některé lokality, ze kterých byly sedimenty
        odebrány, již dnes neexistují.
      </p>
    ),
  },
};
