export const en = {
  menu: {
    menuHomepage: "Homepage",
    menuPeople: "People",
    menuProjects: "Projects",
    menuPublications: "Publications",
    menuLaboratory: "Laboratory",
    menuForStudents: "For Students",
    menuCollections: "Collections",
    menuLinks: "Links",
  },
  footer: {
    addressBrno: "Address Brno:",
    institute: "Institute of Botany of the CAS, v.v.i.",
    name: "Laboratory of Paleoecology",
    streetBrno: "Lidická 25/27",
    zipBrno: "602 00 Brno",
    addressPruhonice: "Address Průhonice:",
    streetPruhonice: "Zámek 1",
    zipPruhonice: "252 43 Průhonice",
    contact: "Contact:",
    contactName: "Přemysl Bobek",
    contactMail: "premysl.bobek@ibot.cas.cz",
    contactPhone: "+420 777 477 785",
    socialSites: "Social sites:",
  },
  people: {
    people: "People",
    head: "Head of the lab",
    deputyHead: "Deputy head of the lab",
    researchers: "Researchers",
    technical: "Technical and administrative staff",
  },
};

export const cz = {
  menu: {
    menuHomepage: "O nás",
    menuPeople: "Lidé",
    menuProjects: "Projekty",
    menuPublications: "Publikace",
    menuLaboratory: "Laboratoř",
    menuForStudents: "Pro Studenty",
    menuCollections: "Sbírky",
    menuLinks: "Odkazy",
    menuContacts: "Kontakty",
  },
  footer: {
    addressBrno: "Adresa Brno:",
    institute: "Botanický ústav AV ČR, v.v.i.",
    name: "Paleoekologická laboratoř",
    streetBrno: "Lidická 25/27",
    zipBrno: "602 00 Brno",
    addressPruhonice: "Adresa Průhonice:",
    streetPruhonice: "Zámek 1",
    zipPruhonice: "252 43 Průhonice",
    contact: "Kontakt:",
    contactName: "Přemysl Bobek",
    contactMail: "premysl.bobek@ibot.cas.cz",
    contactPhone: "+420 777 477 785",
    socialSites: "Sociální sítě:",
  },
  people: {
    people: "Lidé",
    head: "Vedoucí",
    deputyHead: "Zástupce vedoucího",
    researchers: "Vědečtí pracovníci",
    technical: "Techničtí a administrativní pracovníci",
  },
};
